### ISSUE TITLE
按照以下步骤弄的，无法执行任何mip命令，mip init, mip server, mip add index.html均报const错误

### ISSUE THREAD

**Issue by jobsfan** [mipengine/mip-cli#5]
我按照以下步骤搞的
cd /opt
mkdir mip
cd mip
npm init
npm install -g mip-cli --registry=https://registry.npm.taobao.org  这第一遍有乱码，我设置了utf8字符集之后，再搞了一边，貌似没错误

我的系统是ubuntu 16.04 lts

root@ubuntu:/opt/mip# mip init

/usr/local/lib/node_modules/mip-cli/lib/cli.js:8
const program = require('commander');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/mip-cli/bin/mip:3:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
root@ubuntu:/opt/mip#

**Comment by kekee000** [comment]
nodejs 版本 >= 4.0.0才行，之前的版本不支持。
